INSERT INTO INTERVENANT (TYPE, ID, NOM, PRENOM, EMAIL, TEL, MP) VALUES ( 'formateur', 1, 'Bob','noblewomen', 'Bob@bobleprenom.ff', '008865444', 'bob' );
INSERT INTO INTERVENANT (TYPE, ID, NOM, PRENOM, EMAIL, TEL, MP) VALUES ( 'coordinateur', 2, 'Bub','lebub', 'bub@bobleprenom.fr', '0145879745', 'coucou' );
INSERT INTO INTERVENANT (TYPE, ID, NOM, PRENOM, EMAIL, TEL, MP) VALUES ( 'formateur', 3, 'Laper','Sonagé', 'aziz@gmail.cum', '6942069', 'caca' );

INSERT INTO CENTRE(ID, ADRESSE_CENTRE, CODES_POSTAL, NOM_CENTRE, VILLE) VALUES ( 1, '57rue du champion', '69420', 'Champignon', 'Pot' );

INSERT INTO SESSION(ID, DATE_DEBUT, DATE_FIN, CENTRE_ID, COORDINATEUR_ID, FORMATION_ID) VALUES (1, 16-11-2021, 14-07-2022, 1, 2, 1 );

INSERT INTO SEANCE(ID, DATE_DU_JOUR, DEROULEMENT, DURER, OBJECTIF_PEDA, SUPPORT, FORMATEURS_ID, SESSION_ID) VALUES ( 1, 09-03-2022, 'Hervé à dormis en cours comme d habitude', 4, 'Dessiner', null, 3, 1 );

INSERT INTO COMPETENCE(ID, NOM, ACTIVITE_ID) VALUES ( 1, 'C1: Maquettage', 1 );

INSERT INTO ACTIVITE(ID, ACTIVITES_TYPES, NUM_ORDRE, REAC_ID) VALUES ( 1, 'Chibre', 1, 1 );

INSERT INTO REAC(ID, DATE_DEBUT, DURER, LIEN, FORMATION_ID) VALUES ( 1, 01-01-2017, 5, 'https://www.youtube.com', 1 );

INSERT INTO FORMATION(ID, TYPE_FORMATION, CENTRE_ID) VALUES ( 1, 'Concepteur Développeur d Aplication', 1 );

// Table associative

INSERT INTO CENTRE_COORDINATEURS(CENTRES_ID, COORDINATEURS_ID) VALUES ( 1, 2 );

INSERT INTO COMPETENCE_SEANCES(COMPETENCES_ID, SEANCES_ID) VALUES ( 1, 1 );

INSERT INTO SESSION_FORMATEURS(SESSION_ID, FORMATEURS_ID) VALUES ( 1, 3 );

