/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.cda.model;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.*;


@Getter
@Setter
@NoArgsConstructor
@Entity
public class Activiter {
    @Id
    private int id_activite;
    private String activitesTypes;
    /*
    private Set<Competance> competances  = new HashSet<>();
    private Set<Formation> formation  = new HashSet<>();

    public void link(Competance competances_) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void link(Formation _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void unlink(Competance _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Competance _, Iterator<Competance> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

    public void unlink(Formation _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Formation _, Iterator<Formation> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }
*/

}