/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.cda.model;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.*;


// ----------- << imports@AAAAAAF/IbUH0+0X/eI= >>
// ----------- >>

@Entity
@Getter
@Setter
@NoArgsConstructor

public class Competance {
    @Id
    private int id_competence;
    private String nom;
    //private Activiter activiter;
/*
    private Set<Seance>  = new HashSet<>();

    public void link(Activiter _) {
        if (_ != null) {
            _.get().add(this);
        }

        unlink();
        set(_);
    }

    public void link(Seance _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().get().remove(this);
            set(null);
        }
    }

    public void unlink(Seance _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Seance _, Iterator<Seance> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }
*/
// ----------- << class.extras@AAAAAAF/IbUH0+0X/eI= >>
// ----------- >>
}