/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.cda.contenu_seance.model;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.util.*;


@Getter
@Setter
@NoArgsConstructor
@Entity
public class Activite {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String activitesTypes;

    @OneToMany(mappedBy = "activite")
    private List<Competence> competences;
    @ManyToOne
    private Reac reac;

    public Activite(String activiteTypes, List<Competence> competences, Reac reac) {
        this.activitesTypes = activiteTypes;
        this.competences = competences;
        this.reac = reac;
    }
}