/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.cda.contenu_seance.model;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.util.*;

@Entity
@Getter
@Setter
@NoArgsConstructor
@DiscriminatorValue(value = "Formateur")
public class Formateur extends Intervenant{

    @OneToMany(mappedBy = "formateurs")
    private List<Seance> seances;
    @ManyToMany(mappedBy = "formateurs")
    private List<Session> session;

    /*
    public String toFormateur(){
        return "Formateur{"+"id="+this.getId()+", nom='" + this.getNom() +", prenom='" + this.getPrenom() + '\'' + '\'' +"}";
    }
    */
}