/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.cda.contenu_seance.model;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.util.List;


@Entity
@Getter
@Setter
@NoArgsConstructor

public class Formation {
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String typeFormation;

    @OneToMany(mappedBy = "formation")
    private List<Reac> reac;

    @ManyToOne
    private Centre centre;

    public Formation(String typeFormation, List<Reac> reac, Centre centre) {
        this.typeFormation = typeFormation;
        this.reac = reac;
        this.centre = centre;
    }
}