/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.cda.contenu_seance.model;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.util.*;

@Entity
@Getter
@Setter
@NoArgsConstructor

public class Seance {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private Date dateDuJour;
    private int durer;
    private String supportUse;
    private String deroulement;
    private String objectifPeda;

    @ManyToOne
    private Formateur formateur;
    @ManyToOne
    private Session session;
    @ManyToMany(mappedBy = "seances")
    private List<Competence> competances;

    public Seance(Date dateDuJour, int durer, String supportUse, String deroulement, String objectifPeda, Formateur formateur, Session session, List<Competence> competances) {
        this.dateDuJour = dateDuJour;
        this.durer = durer;
        this.supportUse = supportUse;
        this.deroulement = deroulement;
        this.objectifPeda = objectifPeda;
        this.formateur = formateur;
        this.session = session;
        this.competances = competances;
    }
}