@startuml
!theme hacker

start
floating note left: L'utilisateur est inscrit

repeat :L'utilisateur rentre ses identifiants;

backward: Identifiants invalides;
note right: Identifiants = adresse email et mot de passe
repeat while (Les identifiants sont correctes?) is (Non) not (Oui)

:L'utilisateur se connecte correctement;

:Les données et paramètre de l'utilisateur s'affiche;

stop
floating note right: L'utilisateur est connecté dans l'application
@enduml
