@startmindmap
!theme hacker

caption Mind Map
title Application GRETA de suivi
* <&globe>Home
** <&people>Login
*** <&flag> Formateur
**** Dashboard fiche de suivi
**** Formulaire de fiche de suivi
*** <&flag> Coordinateur
**** Dashboard des formulaire de suivi
**** Dashboard de reac
**** Dashboard de centre
**** Dashboard de session
**** Dashboard de activitée
**** Dashboard de compétences
**** Dashboard de savoir faires

@endmindmap
