@startuml

actor Coordinateur
control "CompetenceController" as CC
participant "ReferentielService" as CS
participant "CompetenceRepository" as CR
entity "Competence" as C
database "BDD" as BDD
boundary "View" as V

Coordinateur -> CC: GET/coordonateur/competences
activate CC #FFBBBB


CC -> CS: getAllCompetences()
activate CC #DarkSalmon
activate CS #FFBBBB
CS -> CR: findAll()
activate CR #FFBBBB

CR -> BDD: select * from competence
activate BDD #FFBBBB
BDD --> CR: return
deactivate BDD

CR --> CS: return
deactivate CR
CS --> CC: return
deactivate CS
deactivate CC

CC -> V: dispose dans le template
deactivate CC
activate V #FFBBBB
V -> V: genère l'HTML
V --> Coordinateur: return
deactivate V

@enduml