@startuml

actor Coordinateur
control "CompetenceController" as DC
participant "CompetenceRepository" as CR
entity "Competence" as C
database "BDD" as BDD
boundary "View" as V

Coordinateur -> DC: GET/coordonateur/competences
activate DC #FFBBBB

DC -> CR: getAllCompetences()
activate DC #DarkSalmon
activate CR #FFBBBB

CR -> BDD: select * from competence
activate BDD #FFBBBB
BDD --> CR: return
deactivate BDD

CR --> DC: return
deactivate DC
deactivate CR

DC -> V: dispose dans le template
V -> V: affiche l'HTML
V --> DC: return

DC --> Coordinateur: return
deactivate DC
@enduml