@startuml
!theme hacker

left to right direction
skinparam actorStyle awesome
actor "Formateur" as forma
actor "Coordinateur" as coor
rectangle AppGreta {
  usecase "Renseigner une fiche de séance" as UC1
  usecase "Se connecter" as UC2
  usecase "Export format specifique" as UC3
  usecase "Gerer session" as UC4
  usecase "Gerer Reac" as UC5
  usecase "Gerer formateur" as UC6
  usecase "Gerer formation" as UC10
  usecase "Gerer utilisateur" as UC11
  usecase "Gerer centre" as UC12
}
forma <|- coor
forma -- UC1
UC1 .> UC2 :include
coor -- UC3
coor -- UC4
coor -- UC5
coor -- UC6
coor -- UC10
coor -- UC11
coor -- UC12

@enduml
