@startuml
!theme hacker

left to right direction
skinparam actorStyle awesome
'note top of GRETASuiviSeance: test
actor "Formateur" as forma
actor "Coordinateur" as coor
'actor "Visiteur" as vis
rectangle GRETASuiviSeance {
  usecase "Renseigner une fiche de séance" as UC1
  usecase "Se connecter" as UC2
  usecase "Export format specifique" as UC3
  usecase "Gérer les sessions" as UC4
  usecase "Gérer les Reac" as UC5
  usecase "Gérer les formateurs" as UC6
  usecase "Gérer les formations" as UC10
  usecase "Gérer les utilisateurs" as UC11
  usecase "Gérer les centres" as UC12
  usecase "Import format specifique" as UC13
}
'vis --- UC2
forma <|- coor
forma - UC1
UC1 ..> UC2 :include
coor -- UC3
coor -- UC4
coor -- UC5
coor -- UC6
coor -- UC10
coor -- UC11
coor -- UC12
coor -- UC13

UC3 ..> UC2 :include
UC4 ..> UC2 :include
UC5 ..> UC2 :include
UC6 ..> UC2 :include
UC10 ..> UC2 :include
UC11 ..> UC2 :include
UC12 ..> UC2 :include
UC13 ..> UC2 :include


package "Consulter les formations" {

  (Gérer les formations) <. (Modifier les formations) : extends
  (Ajouter des formations) .> (Gérer les formations) : extends
(Gérer les formations) <.. (Supprimer les formations) : extends
}
@enduml
